# Email Configuration
mail.default.address=01e6fafdce7d09
mail.google.app.password=4dbb18fcc38bf1

# Database Configuration
db.url=jdbc:mysql://localhost:3306/ace_bank
db.user=root
db.password=Tush@262020

# SMTP Server Settings
mail.smtp.host=sandbox.smtp.mailtrap.io
mail.smtp.port=2525
mail.smtp.auth=true